### ISSUE TITLE
Step 2.1

### ISSUE THREAD

**Issue by r-pascua** [HERA-Team/hera-validation#16]
This issue is being raised to come to a consensus on how to complete step 2.1 and who will be contributing to the completion of this validation step. 

I propose that step 2.1 consist of adding realistic gains to all of the effects simulated in step 1.2 (flat EoR P(k) + GSM + point sources + noise). In lieu of a better source of simulated gains, I propose that we use the tools available in `hera_sim.sigchain` to introduce gains to visibilities simulated for step 1.2. The resulting visibilities should be pushed through `redcal`, `abscal`, `smoothcal`, and finally `hera_pspec`. The resulting power spectrum estimate should be compared to the results from step 1.2.

In the top-level repo `README`, it is noted that @aelanman has been assigned to the simulation component of step 1.2. I can perform the analysis of the simulated data for step 1.2 using `hera_pspec`, and I should also be able to apply gains to those visibilities and perform the analysis of the resulting data if it is agreed that `hera_sim.sigchain` will be used for introducing gains. I also suggest that criteria for success are determined by the Validation team after a brief discussion at one of the (upcoming) weekly telecons.

Summary:
* Use simulated visibilities from step 1.2 and tools in `hera_sim.sigchain` to create data for step 2.1.
* Push data through `hera_cal` and `hera_pspec` pipelines; compare results to power spectrum estimates from step 1.2
* @aelanman to do the flat P(k) + GSM + point source simulation
* @r-pascua to add noise and gains with `hera_sim`
* @r-pascua to perform analysis with `hera_cal` and `hera_pspec`
* Validation team should come to a consensus on criteria for success
* Additional details should be discussed during a telecon

Please comment with your thoughts.

**Comment by jsdillon** [comment]
While I think we've passed this test and can close the issue, though there's some spectral structure in the smooth_cal solutions that I wouldn't expect. Namely,

![Screen Shot 2020-03-05 at 10 19 02 AM](https://user-images.githubusercontent.com/5281139/76012225-cdf4d200-5eca-11ea-8887-3666148d097f.png)

The low delay features in the ratio of smooth-to-true gain solutions is troublesome and should probably be investigated. For example, how does it change with the smoothing scale? Is it a problem with CLEAN?

**Comment by r-pascua** [comment]
@jsdillon can you write a quick blurb in #50 when you have the time? In that blurb, could you suggest some level of importance (i.e. is there an upcoming paper that you would like to have the results of a follow-up analysis included in)? It would be very useful for figuring out what level of priority to assign to this.
